### ISSUE TITLE
token is not present

### ISSUE THREAD

**Issue by ChiragPunani** [cashfree/nextgen-android#18]
I have cross checked that both app and backend have sandbox but in Android I am getting the below error.
But not getting error in iOS 
I have tested one another scenario like generated sessionID in android side and set static same sessionID in iOS side and check and again work in iOS not not work in android 
I was using web checkout payment method
`onError : {"message":"token is not present","code":"order_token_invalid","type":"request_failed"}`

**Comment by kishan-cashfree** [comment]
@ChiragPunani This was an intermittent issue. Can you please check again?

**Comment by ChiragPunani** [comment]
@kishan-cashfree Yes Its working fine 
Thanks for the support
